Prompts/Prompt to Create a LinkedIn Post Highlighting ServiceNow Key Features
This prompt helps generate an engaging and professional LinkedIn post to highlight ServiceNow's key features, such as automation, custom workflows, and AI-powered insights. The post is designed to appeal to IT leaders, managers, and decision-makers, showcasing how ServiceNow can drive business efficiency and improve operations. It also includes a headline suggestion, an example of feature impact, and relevant hashtags to boost post visibility. Ideal for promoting ServiceNow’s capabilities and encouraging audience engagement.
=> Prompt to Create a LinkedIn Post Highlighting ServiceNow Key Features

Prompts/Design an optimized notification workflow
A prompt to design an optimized notification system for incident management, consolidating low-priority incident notifications into daily summaries while sending immediate alerts for high-priority incidents. It also outlines the necessary key fields, triggers, and actions for the workflow.
=> Design an optimized notification workflow

Prompts/Prompt for removing all instances of logging from a script, Prompts/Prompt for removing all logging statements from a script, Prompts/Prompt for summarising my assigned stories for a stand-up meeting, Prompts/Prompt to create a description for a catalog item
Addition of 3 GenAI prompts as part of Hacktoberfest
=> CaptainBraddles prompts

Prompts/Prompt to generate ServiceNow Virtual Agent Topic
Prompt to generate ServiceNow Virtual Agent Topic to create an incident or request a catalog item from ServiceNow Virtual Agent which enables the end users to raise incidents or service requests from the Virtual Agent seamlessly.
=> Create Prompt to generate ServiceNow Virtual Agent Topic

Prompts/Create a Security Incident Playbook
This prompt helps create a structured playbook for handling security incidents in ServiceNow. Define steps for detection, analysis, containment, eradication, and recovery to ensure a consistent and adaptable response process.
=> Create Create a Security Incident Playbook

Prompts/Prompt to troubleshoot Discovery Credential Failures in ServiceNow
This prompt helps you troubleshoot and resolve issues related to credential failures in ServiceNow Discovery. By following a step-by-step approach using the RISEN (Review, Identify, Set, Execute, and Notify) framework, it guides you through reviewing error logs, identifying misconfigurations, setting correct credentials, executing tests, and notifying the responsible teams. This prompt is designed to streamline the process of diagnosing credential issues and ensures smoother Discovery operations.
=> Create Prompt to troubleshoot Discovery Credential Failures in ServieNow

Prompts/Prompt for Setting Up a Custom Virtual Agent Conversation Flow in ServiceNow
This prompt assists users in configuring a personalized conversation flow for the Virtual Agent within ServiceNow. It covers the entire setup process, from defining user intents to constructing dialog nodes that effectively address user inquiries. Users will also learn how to integrate backend services to enhance the conversation's functionality by providing real-time data and solutions. The prompt emphasizes best practices for designing an intuitive user experience, enabling organizations to create a powerful and responsive virtual assistant.
=> Create Prompt for Setting Up a Custom Virtual Agent Conversation Flow in servicenow

Prompts/Prompt for Creating Custom UI Actions with GlideAjax
This prompt guides users through the process of creating and implementing custom UI Actions in ServiceNow using GlideAjax for efficient client-server interactions. GlideAjax is a powerful method for improving performance by enabling client-side scripts to communicate with the server without multiple database queries.
=> Create Prompt for Creating Custom UI Actions with GlideAjax

Prompts/Regex_Generator
Act as a Regex Generator and get quick response without any explanations.
=> Regex Generator

Prompts/Create Dashboard and Analyze Trends
A prompt for creating a ServiceNow dashboard and analysis report focused on incident management KPIs. It requires the calculation of two fields that track the time from 'New' status to 'Assigned To' and 'Resolved'. The prompt calls for the creation of a dashboard that visualizes these fields by priority and identifies trends in resolution times. And it also requires the compilation and sentiment analysis of user feedback from resolved incidents and its correlation with resolution times.
=> Prompt to Create Dashboard and Analyze Trends

Prompts/Prompt for automating knowledge article creation from incident problem resulution
This prompt helps users automate the creation of knowledge articles in ServiceNow by extracting information from incident or problem resolution details. It guides the user through each step of the process, from identifying key information to ensuring the article is formatted correctly and categorized appropriately within the knowledge base. This ensures that resolutions are documented efficiently, helping teams build a robust knowledge repository for future reference and problem-solving.
=> Create Prompt for automating knowledge article creation from incident problem resolution

Prompts/Prompt: Discovery Pattern Designer Playbook
In the realm of IT operations and server management, maintaining a precise record of patch details is crucial. Recently, our patching and server teams identified a gap in our Linux Server Configuration Items (CIs)—specifically, the need to capture detailed information about patches, including descriptions and dates. Out-of-the-box (OOB) solutions didn't meet these needs, so we extended our Linux Server discovery pattern to address this challenge.
In this context, AI can significantly enhance our approach. By leveraging AI capabilities, we can automate the extraction and parsing of patch information, reducing manual effort and minimizing errors. AI can analyze patch data in real-time, ensuring that our records are always up to date. Additionally, AI can provide insights into patch trends, …
=> Create Prompt: Discovery Pattern Designer Playbook

Prompts/Prompt to create housekeeping rues for meeting
This prompt asks AI to take on the role of a personal assistant, with a clear instruction to draft housekeeping rules for an upcoming meeting. The success criteria highlight the need for the rules to be clear, concise, and geared towards maintaining a professional, organized, and efficient environment. The exceptions specify avoiding overly formal or complex language to keep the rules practical and easy to follow. Finally, the next steps request that AI not only provide the draft but also include an example that can be used during the meeting.
=> Create Prompt to create housekeeping rues for meeting

Prompts/Prompt to provide best practices which needs to be followed while coding in ServiceNow
This prompt asks an AI to act as a ServiceNow Architect and provide best practices for writing efficient and maintainable code within the ServiceNow platform. It focuses on optimizing performance, adhering to coding standards, ensuring security, and maintaining clean code. Additionally, the AI is expected to give an example of a simple GlideRecord query with best practices and suggest next steps for learning more about ServiceNow development. The RISEN framework guides the AI to deliver structured, actionable insights, ensuring clarity and practical value.
=> Create Prompt to provide best practices which needs to be followed while coding in ServiceNow

Prompts/Convert a regular function to an arrow function
Create Convert a regular function to an arrow function. This is an example prompt for converting a regular javascript function to an arrow function.
=> Create Convert a regular function to an arrow function

Prompts/Help me setup a client-callable (ajax) script include
Create Help me setup a client-callable (ajax) script include and provide examples of its usage
=> Create Help me setup a client-callable (ajax) script include

Prompts/Generate NLU Utterances from Intent.md
This prompt addresses the challenge of manually creating varied Utterances for ServiceNow NLU Intents.
Additionally:
- It provides a structured approach for generating 15 distinct user utterances.
- It includes instructions, steps, and examples to ensure coverage of different communication styles and common user mistakes.
=> Generate NLU Utterances from Intent.md

Prompts/Prompt for Creating a UI Action to Reopen Resolved Incidents
This repository contains a UI Action developed in ServiceNow to allow users to reopen resolved incidents. The action is restricted to users with specific roles.
=> Create Prompt for Creating a UI Action to Reopen Resolved Incidents

Prompts/Prompt for Creating a Scheduled Job to Archive Old Incidents
This repository contains a scheduled job developed in ServiceNow to archive incidents older than one year into a separate archive table.
=> Create Prompt for Creating a Scheduled Job to Archive Old Incidents

Prompts/Generate a comprehensive knowledge article based on the provided ServiceNow change record
The prompt provides a detailed guide for generating knowledge articles from ServiceNow change records. It outlines the necessary input (change record data), output (knowledge article), and considerations for creating effective and informative articles. The prompt includes specific sections for the knowledge article, such as title, summary, affected systems, implementation details, rollback procedure, risk mitigation, knowledge base links, and attachments. Additionally, it emphasizes tailoring the article to the appropriate audience, using clear formatting, including relevant keywords, and implementing version control.
=> Generate a comprehensive knowledge article based on Change Record

Prompts/Generate Technical Document
Prompt to generate Technical document from the Update set in the XML/JSON format
=> Generate Technical Document For Servicenow Implementation

Prompts/Prompt for Generating User Utterances for Meeting Room Booking Intent
Utilize the RISEN framework to instruct an AI model to generate 50 diverse natural language utterances for the "booking a meeting room" intent. The request aims to encompass a variety of user expressions, including formal and casual requests, to reflect different scenarios and specific requirements. The goal is to enhance the system's understanding of user needs and improve the booking process. An example set of utterances will be provided to guide the AI in delivering relevant responses.
=> Create Prompt for Generating User Utterances for Meeting Room Booking Intent

Prompts/Professional Email Generator
This prompt is to generate the email for the Stakeholders for Project updates
=> Create Professional Email

Prompts/Prompt for Presenting Key Features of Now Assist for a Client Meeting
Use the RISEN framework to request AI-generated key features of Now Assist in ServiceNow for a client meeting. The prompt focuses on highlighting core functionalities such as automation, AI-driven insights, and user experience enhancements. Features will be presented in a structured format with brief descriptions to clarify their value and relevance to the client's service management needs. An example feature list will guide the AI response.
=> Create Prompt for Presenting Key Features of Now Assist for a Client Meeting

Prompts/Generate Demo Data
Some starter prompts to ask AI to generate a script that when run, should insert demo data into the instance.
=> Generate Demo Data

Prompts/IncidentManager Class Documentation for ServiceNow.md
Added "IncidentManager Class Documentation for ServiceNow" prompt
=> IncidentManager Class Documentation for ServiceNow

Prompts/ATF Generator For Custom Apps.md
Created a prompt for generating ATF objects for custom scoped app on the ServiceNow Platform.
=> ATF Generator For Custom Apps

Prompts/SQL_To_GlideRecord
This prompt will help you convert SQL queries to appropriate ServiceNow GlideRecord and GlideAggregate code.
=> SQL_To_GlideRecord_Or_GlideAggregate

Prompts/Improving interpersonal skills in workplace, Prompts/Improving interpersonal skills in workplace.md
Hi,
The purpose of this prompt is to provide everyone with a framework for improving your interpersonal skills and fostering positive relationships within the workplace. In order to create a positive workplace and good relationship, it needs to start from us. 
Use this prompt to know what you could have done in order to make the other colleagues feel good and to create a positive environment.
Thanks.
=> Prompt for improving interpersonal skills in workplace

Prompts/Prompt for Scripted Rest API
Prompt for scripted rest api
The objective of this task is to develop a Scripted REST API in ServiceNow that allows external applications to retrieve incident records based on specific query parameters. The API should be designed to accept GET requests, with optional query parameters for priority, state, and assigned_to.
When an external application makes a request to the API, the API should filter the incident records in the incident table according to the provided parameters. The output should be a JSON response containing a list of incidents that match the given criteria, including relevant fields such as incident number, short description, and state.
To ensure robustness, the API must implement error handling to manage invalid parameters gracefully. Specifically, it should return a …
=> Prompt for Scripted Rest API

Prompts/Prompt for Creating an Incident Trends Report
This repository contains a report that analyzes incident trends over the last quarter in ServiceNow. The report focuses on incident distribution by priority level and average resolution times.
=> Create Prompt for Creating an Incident Trends Report

Prompts/Prompt for Identifying Best Practices in ServiceNow Development
The prompt provides a scenario where a developer is tasked with creating a new ServiceNow application for incident management. To ensure the application's quality and efficiency, the developer seeks guidance on ServiceNow development best practices.
=> Prompt for Identifying Best Practices in ServiceNow Development

Prompts/Prompt for Generating Job Descriptions and Screening Resumes
Prompt for Generating Job Descriptions and Screening Resumes
=> Prompt for Generating Job Descriptions and Screening Resumes

Prompts/MOM from the Transcript
Based on the provided meeting transcript, create a concise and informative email that summarizes the key decisions, action items, and next steps discussed.
=> Create MOM from the Transcript

Prompts/Find the common process in the given playbooks
This prompt is helpful to find out the abstraction point for automation and make Action or Subflow reusable.
=> Find the common process in the given playbooks instructions

Prompts/Prompt to Summarize Support Tickets
This prompt is designed to generate a concise and clear summary of support tickets based on provided details. It helps to extract key information such as the issue description, priority, impact, category from the ticket. This helps users quickly understand the urgency and context of the ticket without needing to review all the details.
=> Prompt to Summarize Support Tickets

Prompts/Create User Guide for ITIL users
As a platform owner, I want to create a user guide for my ITIL-specific user including Application Incident Management, change management, Knowledge management and Release management.
=> Create User Guide for ITIL users

Prompts/Prompt to Comprehensive Incident Report for My Groups
This prompt is designed to facilitate the automated generation of incident reports within ServiceNow for all the groups to which the user belongs. It aims to provide a clear and organized overview of both active and resolved incidents, presenting essential details such as incident number, short description, state, priority, assignment group, and created date. By utilizing this prompt, users can efficiently track and manage incidents, ensuring timely resolution and enhanced communication within their teams.
=> Create Prompt to Comprehensive Incident Report for My Groups

Prompts/Create CDMB Dashboard for 3 classes
As a CMDB manager, I want to see a dashboard of CI classes Computer, Server & Router so that my user can see the data in one place, The dashboard contains the 3 different reports
1 report for Computer, 2nd for Server and 3rd for Router which includes the fields Name - Class - Creation Date
Sort by Creation Date
=> Create CDMB Dashboard for 3 classes

Prompts/Workspace_Relationship_Guide
The prompt establishes a mentoring approach where I help you improve workplace relationships by practicing emotional intelligence, empathy, respectful disagreement, rapport-building, and clear, polite communication. This guidance will support you in building stronger, more collaborative connections with colleagues.
=> Workspace_Relationship_Guide
